---
- hosts: all
  become: yes
  gather_facts: yes
  vars:
    docker_compose_version: "1.29.2"
    docker_repo_url: "https://download.docker.com/linux/ubuntu"
    docker_gpg_key_url: "https://download.docker.com/linux/ubuntu/gpg"
    docker_compose_bin: "/usr/local/bin/docker-compose"
    docker_compose_link: "/usr/bin/docker-compose"

  tasks:
    - name: Update apt and install dependencies
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name: Add Docker GPG key
      apt_key:
        url: "{{ docker_gpg_key_url }}"
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] {{ docker_repo_url }} {{ ansible_distribution_release }} stable"
        state: present

    - name: Update apt again after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Download Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: "{{ docker_compose_bin }}"
        mode: '0755'

    - name: Create symbolic link for docker-compose
      file:
        src: "{{ docker_compose_bin }}"
        dest: "{{ docker_compose_link }}"
        state: link

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes
